import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { isLocale, type Locale } from "@/lib/i18n/config";
import { getDictionary } from "@/lib/i18n/dictionaries";

type PageProps = { params: Promise<{ locale: string }> };

type Content = {
  title: string;
  description: string;
  updated: string;
  intro: string;
  sections: Array<{ title: string; paragraphs: string[] }>;
  providersTitle: string;
  providersIntro: string;
  providerLabels: Record<string, string>;
  contactTitle: string;
  contact: string;
};

const providerUrls = {
  RevenueCat: "https://www.revenuecat.com/privacy-policy",
  "App Store": "https://www.apple.com/legal/privacy/data/en/appstore/",
  "Google Play": "https://policies.google.com/privacy",
  DolarAPI: "https://dolarapi.com/docs/legal",
  "ExchangeRate-API": "https://www.exchangerate-api.com/terms",
  Supabase: "https://supabase.com/privacy",
} as const;

const content: Record<Locale, Content> = {
  es: {
    title: "Política de privacidad de Pulso",
    description: "Cómo Pulso trata la información local, la medición opcional de uso y los servicios externos necesarios para la app.",
    updated: "Última actualización: 5 de octubre de 2026",
    intro: "Esta política explica cómo Movilabs trata la información relacionada con Pulso. Está pensada para que sepas qué queda en tu dispositivo, qué pueden tratar servicios externos y qué control tenés sobre tus datos.",
    sections: [
      { title: "Responsable y alcance", paragraphs: ["Pulso es desarrollado por Maximiliano Cuesta, desarrollador independiente radicado en Chubut, Argentina, que opera bajo la marca Movilabs. Para consultas de privacidad o ejercicio de derechos: legal@movilabs.app.", "Pulso es una aplicación de registro y consulta financiera personal. No requiere una cuenta de Pulso y no ofrece sincronización en la nube, respaldo, importación ni restauración de datos."] },
      { title: "Datos que permanecen en tu dispositivo", paragraphs: ["Tus movimientos, categorías, cuentas, presupuestos, metas de ahorro, notas, preferencias, hitos de Ritmo y respuestas cualitativas de la beta se almacenan localmente en tu dispositivo. Movilabs no recibe, almacena ni puede consultar esos registros financieros ni las respuestas de la beta.", "Si desinstalás la app o borrás sus datos desde el sistema operativo, esos datos locales pueden eliminarse de forma irreversible. Como Pulso no ofrece respaldo ni sincronización, Movilabs no puede recuperarlos."] },
      { title: "Medición opcional de uso", paragraphs: ["Pulso prepara en tu dispositivo resúmenes semanales separados sobre Ritmo y el uso de Premium. Sólo se transmiten a Movilabs mediante infraestructura de Supabase después de que elegís expresamente “Permitir resúmenes semanales”. Usar Ritmo o Premium, comprar o restaurar una suscripción no implica aceptar analítica; rechazarla o retirar el consentimiento no limita ninguna función ni impide procesar una compra.", "El tratamiento se basa en tu consentimiento y se usa exclusivamente para analítica y mejora del producto. No se usa para publicidad, seguimiento entre aplicaciones o sitios, perfiles comerciales, decisiones financieras ni venta de datos."] },
      { title: "Contenido de los resúmenes de uso", paragraphs: ["El resumen de Ritmo incluye un identificador aleatorio propio, versión del esquema, semana, versión de la app, plataforma y contadores agregados de interacción, continuidad e hitos. El resumen Premium usa otro identificador aleatorio y contiene contadores agregados de paywalls mediante orígenes predefinidos, plan mensual o anual seleccionado, inicio y resultado de la hoja de compra, restauraciones, cambios del acceso Premium, resolución de límites y uso de familias generales como reportes, contexto económico, exportaciones u organización.", "Los resúmenes no incluyen precios, importes, saldos, monedas, movimientos, notas, comercios, categorías, cuentas, nombres o datos de metas, archivos exportados, respuestas cualitativas de la beta, nombre, email, teléfono, contactos, ubicación precisa, texto libre, identificadores publicitarios ni un identificador estable de instalación, dispositivo, Apple, Google o RevenueCat. Antes de decidir, podés inspeccionar en la app el contenido exacto preparado para compartir."] },
      { title: "Consentimiento, conservación y borrado", paragraphs: ["La decisión, la versión del aviso aceptado, su fecha y las colas de informes se guardan localmente. Podés rechazar la medición o retirar el consentimiento en cualquier momento; al retirarlo, se detienen los envíos futuros. Desde Seguridad y datos también podés solicitar que se borren los informes asociados a los identificadores que aún conserva el dispositivo. Si no hay conexión, la solicitud queda pendiente para reintentarse. Si necesitás asistencia, escribí a legal@movilabs.app e incluí los identificadores visibles en la app, si todavía están disponibles.", "Los informes semanales recibidos se conservan por un máximo de 90 días. Podemos conservar estadísticas agregadas que ya no contengan el identificador del informe. Al no existir una cuenta ni un identificador estable, Movilabs puede no ser capaz de vincular un agregado con una persona o dispositivo ni localizar un informe si su identificador ya no está disponible."] },
      { title: "Exportación y archivos compartidos", paragraphs: ["Podés exportar información como archivo CSV. El archivo se crea en tu dispositivo; una vez que elegís compartirlo, el destinatario, la aplicación o el servicio de almacenamiento que selecciones tratará el archivo según sus propias prácticas.", "Movilabs no recibe una copia de los CSV. Sos responsable de conservarlos, protegerlos y eliminarlos de tus destinos de compartición. Podés eliminar una exportación desde el lugar donde la hayas guardado o compartido."] },
      { title: "Suscripciones y datos técnicos", paragraphs: ["Las compras y suscripciones se procesan a través de App Store o Google Play. Para verificar el acceso Premium, Pulso utiliza RevenueCat. Estos proveedores pueden tratar un identificador anónimo o de dispositivo, datos técnicos, recibos de compra, token de compra o estado de suscripción. Movilabs no recibe datos de tarjetas ni información bancaria.", "Los datos tratados por las tiendas y RevenueCat se usan para procesar, validar, restaurar cuando corresponda y administrar la suscripción. La conservación y eliminación de esos datos se rigen por las políticas de cada proveedor y por las opciones de tu cuenta de tienda."] },
      { title: "Cotizaciones y servicios de datos", paragraphs: ["Pulso puede consultar cotizaciones o tipos de cambio mediante DolarAPI y ExchangeRate-API. Esos servicios no reciben tus movimientos, presupuestos ni categorías: esa información no se envía con la consulta.", "Como ocurre con cualquier conexión a Internet, el proveedor de cotizaciones y la infraestructura que la atiende pueden recibir datos técnicos de la conexión, como dirección IP, fecha, hora, agente de usuario o registros de seguridad. Las cotizaciones pueden pasar por infraestructura de Supabase para su publicación y disponibilidad; esa infraestructura no contiene tus movimientos locales."] },
      { title: "Notificaciones locales", paragraphs: ["Pulso puede mostrar recordatorios locales creados y gestionados por el sistema operativo de tu dispositivo. No se utilizan notificaciones push ni se envían tus datos a un servidor para emitir esos recordatorios."] },
      { title: "Infraestructura, seguridad y transferencias", paragraphs: ["Los resúmenes opcionales de uso se envían cifrados mediante HTTPS a infraestructura de Supabase contratada por Movilabs. Aunque las tablas de medición no guardan una dirección IP, Supabase puede procesar y registrar metadatos técnicos de la conexión —por ejemplo, IP, país aproximado, agente de usuario, fecha, hora y datos de seguridad— conforme a su configuración y política.", "Protegemos el diseño de Pulso mediante minimización y acceso restringido: la información financiera personal permanece local y las tablas de medición no admiten lectura pública. Ningún sistema es completamente infalible; mantené protegido tu dispositivo y revisá los permisos y la seguridad de las aplicaciones con las que compartís archivos.", "RevenueCat, Apple, Google, DolarAPI, ExchangeRate-API y Supabase pueden operar o alojar infraestructura fuera de tu país. El tratamiento de datos técnicos, de suscripción o de medición puede implicar transferencias internacionales bajo las medidas y políticas aplicables de cada proveedor."] },
      { title: "Menores", paragraphs: ["Pulso no está dirigido específicamente a menores. Si sos menor de edad, usá la app con la autorización y supervisión de tu madre, padre o tutor según corresponda."] },
      { title: "Tus derechos y cambios", paragraphs: ["Podés solicitar gratuitamente acceso, actualización, rectificación o eliminación de los datos que Movilabs pudiera tratar y revocar el consentimiento de medición de uso. Según tu jurisdicción, también pueden corresponder derechos de oposición, limitación o portabilidad. Escribí a legal@movilabs.app; podremos pedir información razonable para verificar tu identidad y responderemos dentro de los plazos legales aplicables.", "Dado que tus registros financieros no llegan a Movilabs, podés gestionarlos directamente en tu dispositivo. También podés reclamar ante la Agencia de Acceso a la Información Pública de Argentina y, si estás en Brasil, ante la Autoridade Nacional de Proteção de Dados. Podemos actualizar esta política si cambian Pulso, sus proveedores o las obligaciones aplicables; publicaremos la versión vigente en esta URL e indicaremos su fecha."] },
    ],
    providersTitle: "Políticas de proveedores externos",
    providersIntro: "Consultá las prácticas de privacidad de los servicios que pueden intervenir:",
    providerLabels: { RevenueCat: "Política de privacidad de RevenueCat", "App Store": "Privacidad de App Store (Apple)", "Google Play": "Política de privacidad de Google Play", DolarAPI: "Aviso legal de DolarAPI", "ExchangeRate-API": "Términos de ExchangeRate-API", Supabase: "Política de privacidad de Supabase" },
    contactTitle: "Contacto",
    contact: "Para consultas sobre esta política o privacidad en Pulso, escribinos a:",
  },
  en: {
    title: "Pulso Privacy Policy", description: "How Pulso handles local information, optional usage measurement, and external services needed by the app.", updated: "Last updated: October 5, 2026", intro: "This policy explains how Movilabs handles information related to Pulso. It is designed to make clear what stays on your device, what external services may process, and how you control your information.",
    sections: [
      { title: "Controller and scope", paragraphs: ["Pulso is developed by Maximiliano Cuesta, an independent developer based in Chubut, Argentina, operating under the Movilabs brand. For privacy questions or to exercise your rights: legal@movilabs.app.", "Pulso is a personal finance tracking and reference app. It does not require a Pulso account and does not provide cloud sync, backup, import, or data restoration."] },
      { title: "Data that stays on your device", paragraphs: ["Your transactions, categories, accounts, budgets, savings goals, notes, preferences, Rhythm milestones, and qualitative beta answers are stored locally on your device. Movilabs does not receive, store, or access those financial records or beta answers.", "If you uninstall the app or clear its data through your operating system, local data may be permanently deleted. Since Pulso provides no backup or synchronization, Movilabs cannot restore it."] },
      { title: "Optional usage measurement", paragraphs: ["Pulso prepares separate weekly summaries on your device about Rhythm and Premium usage. They are transmitted to Movilabs through Supabase infrastructure only after you expressly select “Allow weekly summaries.” Using Rhythm or Premium, buying, or restoring a subscription does not mean accepting analytics; declining or withdrawing consent limits no feature and does not prevent purchase processing.", "Processing is based on your consent and used only for product analytics and improvement. It is not used for advertising, cross-app or cross-site tracking, commercial profiling, financial decisions, or data sales."] },
      { title: "Contents of usage summaries", paragraphs: ["The Rhythm summary includes its own random identifier, schema version, week, app version, platform, and aggregate interaction, continuity, and milestone counters. The Premium summary uses a different random identifier and contains aggregate counts of paywalls using predefined sources, monthly or annual plan selection, store-sheet starts and outcomes, restorations, Premium access changes, limit resolution, and use of broad families such as reports, economic context, exports, or organization.", "The summaries do not include prices, amounts, balances, currencies, transactions, notes, merchants, categories, accounts, goal names or details, exported files, qualitative beta answers, name, email, phone number, contacts, precise location, free text, advertising identifiers, or a stable installation, device, Apple, Google, or RevenueCat identifier. Before deciding, you can inspect in the app the exact content prepared for sharing."] },
      { title: "Consent, retention, and deletion", paragraphs: ["Your decision, the accepted notice version and date, and the report queues are stored locally. You can decline measurement or withdraw consent at any time; withdrawal stops future uploads. From Security and data, you can also request deletion of reports associated with identifiers still held by the device. If there is no connection, the request remains pending for retry. If you need assistance, email legal@movilabs.app and include identifiers visible in the app, if still available.", "Received weekly reports are retained for no more than 90 days. We may retain aggregate statistics that no longer contain a report identifier. Because there is no account or stable identifier, Movilabs may be unable to associate an aggregate with a person or device or locate a report if its identifier is no longer available."] },
      { title: "CSV exports and shared files", paragraphs: ["You may export information as a CSV file. The file is created on your device; once you choose to share it, the recipient, app, or storage service you select handles it under its own practices.", "Movilabs does not receive a copy of CSV exports. You are responsible for retaining, protecting, and deleting them from the places where you save or share them."] },
      { title: "Subscriptions and technical data", paragraphs: ["Purchases and subscriptions are processed by the App Store or Google Play. Pulso uses RevenueCat to verify Premium access. These providers may process an anonymous or device identifier, technical data, purchase receipts, purchase token, or subscription status. Movilabs does not receive card or banking information.", "Store and RevenueCat data is used to process, validate, restore where applicable, and manage subscriptions. Retention and deletion are governed by each provider’s policies and your store-account choices."] },
      { title: "Exchange rates and data services", paragraphs: ["Pulso may request exchange rates through DolarAPI and ExchangeRate-API. Those services do not receive your transactions, budgets, or categories; that information is not sent with a request.", "As with any internet connection, rate providers and their infrastructure may receive connection data such as IP address, date, time, user agent, or security logs. Rates may pass through Supabase infrastructure for publication and availability; that infrastructure does not contain your local transactions."] },
      { title: "Local notifications", paragraphs: ["Pulso may show reminders created and managed locally by your device’s operating system. It does not use push notifications or send your data to a server to issue reminders."] },
      { title: "Infrastructure, security, and transfers", paragraphs: ["Optional usage summaries are encrypted in transit using HTTPS and sent to Supabase infrastructure engaged by Movilabs. Although the measurement tables do not store an IP address, Supabase may process and log connection metadata—such as IP address, approximate country, user agent, date, time, and security information—under its configuration and policy.", "Pulso applies data minimization and restricted access: personal financial information stays local and the measurement tables are not publicly readable. No system is completely fail-safe; protect your device and review the permissions and security of apps used to share files.", "RevenueCat, Apple, Google, DolarAPI, ExchangeRate-API, and Supabase may operate or host infrastructure outside your country. Their handling of technical, subscription, or measurement data may involve international transfers under each provider’s applicable safeguards and policies."] },
      { title: "Children", paragraphs: ["Pulso is not specifically directed to children. If you are under the age of majority, use the app with parent or guardian authorization and supervision where applicable."] },
      { title: "Your rights and policy changes", paragraphs: ["You may request, free of charge, access to, updating, correction, or deletion of data Movilabs may process and withdraw your usage-measurement consent. Depending on your jurisdiction, you may also have rights to object, restrict processing, or portability. Email legal@movilabs.app; we may request reasonable information to verify your identity and will respond within applicable legal deadlines.", "Because financial records do not reach Movilabs, manage them directly on your device. You may also lodge a complaint with Argentina’s Agency for Access to Public Information and, if you are in Brazil, with the National Data Protection Authority. We may update this policy when Pulso, its providers, or applicable obligations change; we will publish the current version at this URL and display its date."] },
    ], providersTitle: "External providers’ policies", providersIntro: "See the privacy practices of services that may be involved:", providerLabels: { RevenueCat: "RevenueCat Privacy Policy", "App Store": "App Store Privacy (Apple)", "Google Play": "Google Privacy Policy", DolarAPI: "DolarAPI legal notice", "ExchangeRate-API": "ExchangeRate-API Terms", Supabase: "Supabase Privacy Policy" }, contactTitle: "Contact", contact: "For questions about this policy or privacy in Pulso, email:",
  },
  pt: {
    title: "Política de privacidade do Pulso", description: "Como o Pulso trata informações locais, a medição opcional de uso e os serviços externos necessários ao app.", updated: "Última atualização: 5 de outubro de 2026", intro: "Esta política explica como a Movilabs trata as informações relacionadas ao Pulso. Ela esclarece o que fica no seu dispositivo, o que serviços externos podem tratar e como você controla suas informações.",
    sections: [
      { title: "Responsável e escopo", paragraphs: ["O Pulso é desenvolvido por Maximiliano Cuesta, desenvolvedor independente radicado em Chubut, Argentina, que opera sob a marca Movilabs. Para consultas de privacidade ou exercício de direitos: legal@movilabs.app.", "O Pulso é um aplicativo de registro e consulta financeira pessoal. Não exige uma conta Pulso e não oferece sincronização em nuvem, backup, importação ou restauração de dados."] },
      { title: "Dados que ficam no seu dispositivo", paragraphs: ["Seus lançamentos, categorias, contas, orçamentos, metas de poupança, notas, preferências, marcos do Ritmo e respostas qualitativas do beta ficam armazenados localmente no dispositivo. A Movilabs não recebe, armazena nem acessa esses registros financeiros nem as respostas do beta.", "Se você desinstalar o aplicativo ou apagar seus dados pelo sistema operacional, os dados locais poderão ser excluídos permanentemente. Como o Pulso não oferece backup nem sincronização, a Movilabs não pode restaurá-los."] },
      { title: "Medição opcional de uso", paragraphs: ["O Pulso prepara no dispositivo resumos semanais separados sobre o Ritmo e o uso do Premium. Eles só são transmitidos à Movilabs pela infraestrutura da Supabase depois que você escolhe expressamente “Permitir resumos semanais”. Usar o Ritmo ou o Premium, comprar ou restaurar uma assinatura não significa aceitar análises; recusar ou retirar o consentimento não limita recursos nem impede o processamento da compra.", "O tratamento se baseia no seu consentimento e é usado exclusivamente para análise e melhoria do produto. Ele não é usado para publicidade, rastreamento entre apps ou sites, criação de perfis comerciais, decisões financeiras ou venda de dados."] },
      { title: "Conteúdo dos resumos de uso", paragraphs: ["O resumo do Ritmo inclui seu próprio identificador aleatório, versão do esquema, semana, versão do app, plataforma e contadores agregados de interação, continuidade e marcos. O resumo Premium usa outro identificador aleatório e contém contadores agregados de paywalls com origens predefinidas, plano mensal ou anual selecionado, início e resultado da folha da loja, restaurações, alterações do acesso Premium, resolução de limites e uso de famílias gerais como relatórios, contexto econômico, exportações ou organização.", "Os resumos não incluem preços, valores, saldos, moedas, lançamentos, notas, estabelecimentos, categorias, contas, nomes ou dados de metas, arquivos exportados, respostas qualitativas do beta, nome, email, telefone, contatos, localização precisa, texto livre, identificadores de publicidade nem um identificador estável de instalação, dispositivo, Apple, Google ou RevenueCat. Antes de decidir, você pode inspecionar no app o conteúdo exato preparado para compartilhamento."] },
      { title: "Consentimento, retenção e exclusão", paragraphs: ["A decisão, a versão e a data do aviso aceito e as filas de relatórios ficam armazenadas localmente. Você pode recusar a medição ou retirar o consentimento a qualquer momento; a retirada interrompe futuros envios. Em Segurança e dados, também pode solicitar a exclusão dos relatórios associados aos identificadores ainda mantidos pelo dispositivo. Sem conexão, a solicitação fica pendente para nova tentativa. Se precisar de ajuda, escreva para legal@movilabs.app e inclua os identificadores visíveis no app, se ainda estiverem disponíveis.", "Os relatórios semanais recebidos são mantidos por no máximo 90 dias. Podemos conservar estatísticas agregadas que já não contenham o identificador do relatório. Como não existe conta nem identificador estável, a Movilabs pode não conseguir associar um agregado a uma pessoa ou dispositivo nem localizar um relatório se seu identificador já não estiver disponível."] },
      { title: "Exportações CSV e arquivos compartilhados", paragraphs: ["Você pode exportar informações em um arquivo CSV. O arquivo é criado no seu dispositivo; ao compartilhá-lo, o destinatário, aplicativo ou serviço de armazenamento escolhido o tratará conforme suas próprias práticas.", "A Movilabs não recebe uma cópia das exportações CSV. Você é responsável por mantê-las, protegê-las e excluí-las dos locais onde as salvar ou compartilhar."] },
      { title: "Assinaturas e dados técnicos", paragraphs: ["Compras e assinaturas são processadas pela App Store ou Google Play. O Pulso usa o RevenueCat para verificar o acesso Premium. Esses provedores podem tratar um identificador anônimo ou do dispositivo, dados técnicos, recibos de compra, token de compra ou estado da assinatura. A Movilabs não recebe dados de cartão ou bancários.", "Os dados tratados pelas lojas e pelo RevenueCat servem para processar, validar, restaurar quando aplicável e administrar a assinatura. A retenção e exclusão seguem as políticas de cada provedor e as opções da sua conta de loja."] },
      { title: "Cotações e serviços de dados", paragraphs: ["O Pulso pode consultar cotações ou taxas de câmbio por meio do DolarAPI e ExchangeRate-API. Esses serviços não recebem seus lançamentos, orçamentos ou categorias: essas informações não são enviadas na consulta.", "Como em qualquer conexão à Internet, provedores de cotação e sua infraestrutura podem receber dados técnicos da conexão, como endereço IP, data, hora, agente do usuário ou registros de segurança. As cotações podem passar pela infraestrutura do Supabase para publicação e disponibilidade; essa infraestrutura não contém seus lançamentos locais."] },
      { title: "Notificações locais", paragraphs: ["O Pulso pode mostrar lembretes criados e gerenciados localmente pelo sistema operacional do seu dispositivo. Não usa notificações push nem envia seus dados a um servidor para emitir lembretes."] },
      { title: "Infraestrutura, segurança e transferências", paragraphs: ["Os resumos opcionais de uso são enviados com criptografia em trânsito por HTTPS para a infraestrutura da Supabase contratada pela Movilabs. Embora as tabelas de medição não armazenem um endereço IP, a Supabase pode processar e registrar metadados técnicos da conexão —como IP, país aproximado, agente do usuário, data, hora e informações de segurança— conforme sua configuração e política.", "O Pulso aplica minimização e acesso restrito: as informações financeiras pessoais permanecem locais e as tabelas de medição não permitem leitura pública. Nenhum sistema é totalmente infalível; proteja seu dispositivo e revise as permissões e a segurança dos aplicativos usados para compartilhar arquivos.", "RevenueCat, Apple, Google, DolarAPI, ExchangeRate-API e Supabase podem operar ou hospedar infraestrutura fora do seu país. O tratamento de dados técnicos, de assinatura ou de medição pode envolver transferências internacionais conforme as medidas e políticas aplicáveis de cada provedor."] },
      { title: "Menores", paragraphs: ["O Pulso não é direcionado especificamente a menores. Se você não atingiu a maioridade, use o app com autorização e supervisão de pai, mãe ou responsável, quando aplicável."] },
      { title: "Seus direitos e alterações", paragraphs: ["Você pode solicitar gratuitamente acesso, atualização, correção ou exclusão dos dados que a Movilabs possa tratar e retirar seu consentimento para medição de uso. Conforme sua jurisdição, também podem existir direitos de oposição, limitação ou portabilidade. Escreva para legal@movilabs.app; poderemos solicitar informações razoáveis para verificar sua identidade e responderemos nos prazos legais aplicáveis.", "Como registros financeiros não chegam à Movilabs, gerencie-os diretamente no dispositivo. Você também pode apresentar uma reclamação à Agência de Acesso à Informação Pública da Argentina e, se estiver no Brasil, à Autoridade Nacional de Proteção de Dados. Podemos atualizar esta política quando o Pulso, seus provedores ou as obrigações aplicáveis mudarem; publicaremos a versão atual neste URL e indicaremos sua data."] },
    ], providersTitle: "Políticas dos provedores externos", providersIntro: "Consulte as práticas de privacidade dos serviços que podem estar envolvidos:", providerLabels: { RevenueCat: "Política de privacidade do RevenueCat", "App Store": "Privacidade da App Store (Apple)", "Google Play": "Política de privacidade do Google", DolarAPI: "Aviso legal do DolarAPI", "ExchangeRate-API": "Termos do ExchangeRate-API", Supabase: "Política de privacidade do Supabase" }, contactTitle: "Contato", contact: "Para dúvidas sobre esta política ou privacidade no Pulso, escreva para:",
  },
};

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { locale } = await params;
  if (!isLocale(locale)) return {};
  const t = content[locale];
  return {
    title: t.title,
    description: t.description,
    alternates: { canonical: `/${locale}/pulso/privacy`, languages: { es: "/es/pulso/privacy", en: "/en/pulso/privacy", pt: "/pt/pulso/privacy" } },
    openGraph: { type: "website", url: `https://www.movilabs.app/${locale}/pulso/privacy`, title: t.title, description: t.description },
  };
}

export default async function PulsoPrivacyPage({ params }: PageProps) {
  const { locale } = await params;
  if (!isLocale(locale)) notFound();
  const dictionary = getDictionary(locale);
  const t = content[locale];

  return <div className="site-shell min-h-screen overflow-x-clip">
    <div aria-hidden className="site-grid" />
    <SiteHeader locale={locale} currentPath="/pulso/privacy" labels={dictionary.nav} />
    <main className="site-container py-16 sm:py-20"><article className="frosted max-w-4xl rounded-3xl p-7 sm:p-10">
      <header className="space-y-4"><p className="text-xs uppercase tracking-[0.18em] text-muted">Pulso · Legal</p><h1 className="font-display text-3xl font-medium tracking-tight text-ink sm:text-4xl">{t.title}</h1><p className="text-sm text-muted">{t.updated}</p><p className="max-w-3xl text-base leading-relaxed text-muted sm:text-lg">{t.intro}</p></header>
      {t.sections.map((section) => <section key={section.title} className="mt-10 space-y-4"><h2 className="font-display text-xl font-medium text-ink sm:text-2xl">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="text-base leading-relaxed text-muted">{paragraph}</p>)}</section>)}
      <section className="mt-10 space-y-4"><h2 className="font-display text-xl font-medium text-ink sm:text-2xl">{t.providersTitle}</h2><p className="text-base leading-relaxed text-muted">{t.providersIntro}</p><ul className="list-disc space-y-2 pl-5 text-base text-muted">{Object.entries(providerUrls).map(([name, url]) => <li key={name}><a className="focus-ring rounded text-ink underline decoration-line underline-offset-4 hover:text-accent" href={url} target="_blank" rel="noreferrer">{t.providerLabels[name]}</a></li>)}</ul></section>
      <section className="mt-10 space-y-4"><h2 className="font-display text-xl font-medium text-ink sm:text-2xl">{t.contactTitle}</h2><p className="text-base leading-relaxed text-muted">{t.contact}</p><a href="mailto:legal@movilabs.app" className="focus-ring inline-flex rounded-xl border border-line bg-soft px-4 py-2.5 text-base font-medium text-ink transition-colors duration-200 hover:border-accent hover:text-accent">legal@movilabs.app</a></section>
    </article></main>
    <SiteFooter locale={locale} privacyLabel={dictionary.footer.privacy} />
  </div>;
}
